package com.example.beirutrun.city

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import java.io.File
import java.util.concurrent.Executors
import kotlin.random.Random

/**
 * Plays the game's sound effects with low latency. The sounds are generated by [SoundSynth] once,
 * written to the cache as WAV files, and loaded into a [SoundPool]; sounds asked for before they
 * finish loading are skipped.
 */
class SoundEffects(context: Context) {

    private val pool = SoundPool.Builder()
        .setMaxStreams(8)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()
        )
        .build()

    private val dir = File(context.cacheDir, "sfx_v$VERSION").apply { mkdirs() }
    @Volatile private var shot = 0
    @Volatile private var ouch = intArrayOf()
    @Volatile private var death = 0

    init {
        // Generating takes a moment, so do it off the main thread.
        val worker = Executors.newSingleThreadExecutor()
        worker.execute {
            shot = load("shot") { SoundSynth.gunshot() }
            // A few pitches so repeated hits don't all sound identical.
            ouch = floatArrayOf(0.92f, 1f, 1.1f).mapIndexed { i, p -> load("ouch$i") { SoundSynth.ouch(p) } }.toIntArray()
            death = load("death") { SoundSynth.death() }
        }
        worker.shutdown()
    }

    private fun load(name: String, make: () -> FloatArray): Int {
        val file = File(dir, "$name.wav")
        if (!file.exists()) file.writeBytes(SoundSynth.toWav(make()))
        return pool.load(file.path, 1)
    }

    /**
     * A gunshot; [volume] 0..1 (quieter for other players' shots far away). The pistol is the
     * same shot played faster: higher and snappier than the AK-47's boom.
     */
    fun shoot(volume: Float = 1f, weapon: Weapon = Weapon.AK47) {
        val pitch = if (weapon == Weapon.PISTOL) 1.4f else 0.95f
        play(shot, volume, pitch + Random.nextFloat() * 0.1f)
    }

    /** "Ay!" when a bullet hits someone. */
    fun ouch(volume: Float = 1f) {
        val sounds = ouch
        if (sounds.isNotEmpty()) play(sounds[Random.nextInt(sounds.size)], volume, 1f)
    }

    /** The groan when a player is killed. */
    fun death(volume: Float = 1f) = play(death, volume, 1f)

    private fun play(id: Int, volume: Float, rate: Float) {
        if (id == 0 || volume <= 0.01f) return
        val v = volume.coerceIn(0f, 1f)
        pool.play(id, v, v, 1, 0, rate)
    }

    fun release() = pool.release()

    private companion object {
        /** Bump when the synthesized sounds change, so old cached files are not reused. */
        const val VERSION = 1
    }
}
