package com.example.beirutrun.city

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.os.Handler
import android.os.Looper
import java.io.File
import java.util.concurrent.Executors
import kotlin.random.Random

/**
 * Plays the game's sound effects with low latency. Gunshots and reload sounds are real
 * recordings in `assets/sounds/` (see [RECORDED] and [MECHANICS]); anything without one, and the
 * cries, is generated by [SoundSynth] once and written to the cache as WAV files. All are loaded
 * into a [SoundPool]; sounds asked for before they finish loading are skipped.
 */
class SoundEffects(context: Context) {

    private val pool = SoundPool.Builder()
        // Automatic fire overlaps many shots, each ringing for about a second.
        .setMaxStreams(16)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()
        )
        .build()

    private val dir = File(context.cacheDir, "sfx_v$VERSION").apply { mkdirs() }
    private val assets = context.assets
    private val main = Handler(Looper.getMainLooper())
    /** Marks the reload sounds waiting to play, so switching guns can cancel them. */
    private val reloadToken = Any()
    /** Each kind of shot: its sound, and the playback rate that turns the recording into it. */
    @Volatile private var shots = emptyMap<ShotSound, Pair<Int, Float>>()
    @Volatile private var ouch = intArrayOf()
    @Volatile private var death = 0
    /** The rank-up fanfare: `assets/sounds/rank_up.wav` if it is there (0 = none, silent). */
    @Volatile private var rankUp = 0
    /** Gun mechanics, each a sound and its playback rate (like [shots]). */
    @Volatile private var magOut = NONE
    @Volatile private var magIn = NONE
    @Volatile private var rack = NONE
    @Volatile private var slide = NONE
    @Volatile private var bolt = NONE
    @Volatile private var roundIn = NONE
    @Volatile private var cover = NONE
    @Volatile private var belt = NONE
    /** Grenades: the throw, and what each kind sounds like going off. */
    @Volatile private var pin = 0
    @Volatile private var bursts = emptyMap<GrenadeKind, Int>()
    @Volatile private var ringing = 0

    init {
        // Generating takes a moment, so do it off the main thread.
        val worker = Executors.newSingleThreadExecutor()
        worker.execute {
            // Real recordings where there are some (each file loaded once), else the synthesized shot.
            val files = HashMap<String, Int>()
            shots = ShotSound.entries.associateWith { kind ->
                val recorded = RECORDED[kind]?.let { (file, rate) -> loadAsset(file, files)?.let { it to rate } }
                recorded ?: (load("shot_${kind.name.lowercase()}") { SoundSynth.gunshot(kind) } to 1f)
            }
            // A few pitches so repeated hits don't all sound identical.
            ouch = floatArrayOf(0.92f, 1f, 1.1f).mapIndexed { i, p -> load("ouch$i") { SoundSynth.ouch(p) } }.toIntArray()
            death = load("death") { SoundSynth.death() }
            rankUp = loadAsset("rank_up", files) ?: 0
            fun mechanic(name: String, synth: () -> FloatArray): Pair<Int, Float> =
                MECHANICS[name]?.let { (file, rate) -> loadAsset(file, files)?.let { it to rate } }
                    ?: (load(name) { synth() } to 1f)
            magOut = mechanic("mag_out") { SoundSynth.magazineOut() }
            magIn = mechanic("mag_in") { SoundSynth.magazineIn() }
            rack = mechanic("rack") { SoundSynth.rack() }
            slide = mechanic("slide") { SoundSynth.rack() }
            bolt = mechanic("bolt") { SoundSynth.bolt() }
            roundIn = mechanic("round_in") { SoundSynth.roundIn() }
            cover = mechanic("feed_cover") { SoundSynth.feedCover() }
            belt = mechanic("belt") { SoundSynth.beltRattle() }
            pin = load("grenade_pin") { SoundSynth.grenadePin() }
            bursts = mapOf(
                GrenadeKind.FRAG to load("grenade_frag") { SoundSynth.explosion() },
                GrenadeKind.FLASH to load("grenade_flash") { SoundSynth.flashbang() },
                GrenadeKind.SMOKE to load("grenade_smoke") { SoundSynth.smokeHiss() },
                GrenadeKind.MOLOTOV to load("grenade_molotov") { SoundSynth.molotov() },
            )
            ringing = load("ear_ringing") { SoundSynth.earRinging() }
        }
        worker.shutdown()
    }

    /** A recording in `assets/sounds/` (null if it isn't there), loaded once per file. */
    private fun loadAsset(file: String, loaded: MutableMap<String, Int>): Int? = loaded[file] ?: runCatching {
        assets.openFd("sounds/$file.wav").use { pool.load(it, 1) }
    }.getOrNull()?.also { loaded[file] = it }

    private fun load(name: String, make: () -> FloatArray): Int {
        val file = File(dir, "$name.wav")
        if (!file.exists()) file.writeBytes(SoundSynth.toWav(make()))
        return pool.load(file.path, 1)
    }

    /**
     * [weapon]'s shot; [volume] 0..1 (quieter for other players' shots far away). A bolt-action
     * rifle then works its bolt, the way a sniper does between shots.
     */
    fun shoot(volume: Float = 1f, weapon: Weapon = Weapon.AK47) {
        val (id, rate) = shots[weapon.sound] ?: return
        play(id, volume, rate * (0.97f + Random.nextFloat() * 0.06f))
        if (weapon.boltAction) main.postDelayed({ play(bolt, volume * 0.7f) }, BOLT_DELAY_MS)
    }

    /**
     * The sounds of changing [weapon]'s magazine (or belt, or loading a bolt action's rounds),
     * spread over its reload time the way the real gun is handled: out, in, and the slide,
     * charging handle or bolt, timed to finish as the reload does.
     */
    fun reload(weapon: Weapon) {
        cancelReload()
        val ms = weapon.reloadSeconds * 1000f
        fun at(fraction: Float, sound: () -> Pair<Int, Float>, pitch: Float = 1f) = main.postAtTime(
            { play(sound(), 0.9f, pitch) }, reloadToken, android.os.SystemClock.uptimeMillis() + (ms * fraction).toLong(),
        )
        when {
            weapon == Weapon.M249 -> {
                at(0.06f, { cover })                                  // feed cover up
                at(0.2f, { magOut })                                  // empty pouch off
                at(0.4f, { magIn })                                   // new pouch on
                at(0.58f, { belt })                                   // belt laid in the tray
                at(0.74f, { cover }, 0.85f)                           // cover slammed shut
                at(0.86f, { rack })                                   // charging handle
            }
            weapon == Weapon.M24 -> {
                // Internal magazine: bolt open, five rounds pressed in, bolt closed.
                at(0.04f, { bolt })
                for (i in 0 until weapon.magazine) at(0.2f + i * 0.1f, { roundIn }, 0.95f + i * 0.02f)
                at(0.8f, { bolt })
            }
            weapon.boltAction -> {
                at(0.15f, { magOut })
                at(0.45f, { magIn })
                at(0.74f, { bolt })
            }
            weapon.slot == GunSlot.PISTOL -> {
                at(0.1f, { magOut })
                at(0.35f, { magIn })
                at(0.66f, { slide })                                  // slide released forward
            }
            else -> {
                at(0.1f, { magOut })
                at(0.4f, { magIn })
                at(0.72f, { rack })                                   // charging handle
            }
        }
    }

    /** Stops the reload sounds still to come (the reload was cut short). */
    fun cancelReload() = main.removeCallbacksAndMessages(reloadToken)

    /** A grenade's pin pulled and thrown. */
    fun grenadeThrow(volume: Float = 1f) = play(pin, volume, 1f)

    /** A grenade of [kind] going off; [volume] 0..1, quieter the further away it is. */
    fun grenadeBurst(kind: GrenadeKind, volume: Float = 1f) {
        val id = bursts[kind] ?: return
        play(id, volume, 0.95f + Random.nextFloat() * 0.1f)
    }

    /** The ears ringing after being blinded by a flashbang; louder the worse it was. */
    fun earRinging(volume: Float) = play(ringing, volume, 1f)

    /** "Ay!" when a bullet hits someone. */
    fun ouch(volume: Float = 1f) {
        val sounds = ouch
        if (sounds.isNotEmpty()) play(sounds[Random.nextInt(sounds.size)], volume, 1f)
    }

    /** The groan when a player is killed. */
    fun death(volume: Float = 1f) = play(death, volume, 1f)

    /** Played when the player reaches a new rank. Silent until `assets/sounds/rank_up.wav` is added. */
    fun rankUp(volume: Float = 1f) = play(rankUp, volume, 1f)

    /** A sound with its own playback rate (see [MECHANICS]), times [pitch]. */
    private fun play(sound: Pair<Int, Float>, volume: Float, pitch: Float = 1f) = play(sound.first, volume, sound.second * pitch)

    private fun play(id: Int, volume: Float, rate: Float) {
        if (id == 0 || volume <= 0.01f) return
        val v = volume.coerceIn(0f, 1f)
        pool.play(id, v, v, 1, 0, rate)
    }

    fun release() {
        cancelReload()
        main.removeCallbacksAndMessages(null)
        pool.release()
    }

    private companion object {
        /**
         * Real gunshot recordings in `assets/sounds/` (credits in `assets/sounds/CREDITS.txt`) and
         * the playback rate that makes each kind of shot from them: slower is deeper and heavier.
         * Kinds without a recording use SoundSynth.gunshot.
         */
        val RECORDED = mapOf(
            ShotSound.PISTOL to ("pistol_9mm" to 1f),     // 9 mm pistol
            ShotSound.SMG to ("smg_uzi" to 1f),           // Uzi, 9 mm like the MP5
            ShotSound.MAGNUM to ("pistol_9mm" to 0.8f),   // Desert Eagle: the 9 mm, heavier
            ShotSound.RIFLE to ("rifle_ak47" to 1f),      // AK-47
            ShotSound.LMG to ("lmg_fnmag" to 1f),         // FN MAG machine gun
            ShotSound.SNIPER to ("sniper_fnfal" to 1f),   // FN FAL, 7.62 mm
            ShotSound.FIFTY to ("sniper_fnfal" to 0.78f), // Barrett: the 7.62 mm, deeper
        )

        /**
         * Real recordings of gun mechanics, by the name reload() uses, with their playback rate.
         * The bolt action and the machine gun's feed cover are the charging handle and the
         * magazine going in, played heavier; a round pressed in is the magazine catch, lighter.
         */
        val MECHANICS = mapOf(
            "mag_out" to ("mag_out" to 1f),
            "mag_in" to ("mag_in" to 1f),
            "rack" to ("rifle_charge" to 1f),
            "slide" to ("pistol_slide" to 1f),
            "bolt" to ("rifle_charge" to 0.85f),
            "round_in" to ("mag_out" to 1.35f),
            "feed_cover" to ("mag_in" to 0.75f),
        )

        private val NONE = 0 to 1f
        /** Bump when the synthesized sounds change, so old cached files are not reused. */
        const val VERSION = 2
        /** After a bolt-action shot, the bolt is worked this much later. */
        const val BOLT_DELAY_MS = 450L
    }
}
